### PR TITLE
fixes #52 support cobertura class level coverage

### LINKED ISSUE #52: Support cobertura class level coverage
Currently only package coverages are printed.
Some languages don't have a package concept so it would make sense to output class level coverage below the package.
This could be configurable.

### PR DESCRIPTION
**Pull request by tm1000**
fixes #52

I'm not sure what to do if sources has more than one string but I suppose that can be for the next iteration of this (or when someone sends me one with multiples)

### CODE REVIEW

**Review by hsingh-texada — APPROVED** [review]

**Comment by hsingh-texada** [comment]
@tm1000 This is mildly related, would you also able to add a flag to only add classes for which coverage changed in the MD file.. If a project has thousands of classes, it would end up being a really long file and difficult to read in a PR context.

**Comment by tm1000** [comment]
@hsingh-texada I added #58 which I might get to tomorrow evening if all goes well.

**Review by kuhnroyal — APPROVED** [review]

**Comment by kuhnroyal** [comment]
Awesome work! @hsingh-texada Also really love this suggestion!

**Review by GameGamer43 — APPROVED** [review]

**Review by berrugo — APPROVED** [review]

**Comment by kuhnroyal** [comment]
I am getting an error.

> Error: Cannot read properties of undefined (reading 'map')

See https://github.com/cfug/dio/actions/runs/9137019517/job/25139180215

**Pull request merged**
